# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20161015_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='static/blog/pictures'),
        ),
    ]
