# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20161015_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/blog/pictures'),
        ),
    ]
